[package]
name = "midiportlist"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
authors = ["Oliver Rockstedt <info@sourcebox.de>"]
description = "CLI tool to list available MIDI ports"
license = "MIT"
repository = "https://github.com/sourcebox/midiportlist"
categories = ["command-line-utilities", "multimedia"]
keywords = ["midi", "terminal"]

[dependencies]
midir = { version = "0.11.0", features = ["winrt"] }

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[profile.release]
strip = true
